#!/bin/sh

set -e

[ -f /etc/sysconfig/influxdb-srelay ] && . /etc/sysconfig/influxdb-srelay

startInfluxDBSrelay() {
  if [ -x /bin/systemctl ] ; then
		/bin/systemctl start influxdb-srelay.service
	elif [ -x /etc/init.d/influxdb-srelay ] ; then
		/etc/init.d/influxdb-srelay start
	elif [ -x /etc/rc.d/init.d/influxdb-srelay ] ; then
		/etc/rc.d/init.d/influxdb-srelay start
	fi
}

stopInfluxDBSrelay() {
	if [ -x /bin/systemctl ] ; then
		/bin/systemctl stop influxdb-srelay.service > /dev/null 2>&1 || :
	elif [ -x /etc/init.d/influxdb-srelay ] ; then
		/etc/init.d/influxdb-srelay stop
	elif [ -x /etc/rc.d/init.d/influxdb-srelay ] ; then
		/etc/rc.d/init.d/influxdb-srelay stop
	fi
}

# Initial installation: $1 == 1
# Upgrade: $1 == 2, and configured to restart on upgrade
if [ $1 -eq 1 ] ; then
	[ -z "$INFLUXDB_SRELAY_USER" ] && INFLUXDB_SRELAY_USER="influxdb-srelay"
	[ -z "$INFLUXDB_SRELAY_GROUP" ] && INFLUXDB_SRELAY_GROUP="influxdb-srelay"
	if ! getent group "$INFLUXDB_SRELAY_GROUP" > /dev/null 2>&1 ; then
    groupadd -r "$INFLUXDB_SRELAY_GROUP"
	fi
	if ! getent passwd "$INFLUXDB_SRELAY_USER" > /dev/null 2>&1 ; then
    useradd -r -g influxdb-srelay -d /usr/share/influxdb-srelay -s /sbin/nologin \
    -c "influxdb-srelay user" influxdb-srelay
	fi

 	# Set user permissions on /var/log/influxdb-srelay, /var/lib/influxdb-srelay
	mkdir -p /var/log/influxdb-srelay /var/lib/influxdb-srelay
	chown -R $INFLUXDB_SRELAY_USER:$INFLUXDB_SRELAY_GROUP /var/log/influxdb-srelay /var/lib/influxdb-srelay
	chmod 755 /var/log/influxdb-srelay /var/lib/influxdb-srelay

	# configuration files should not be modifiable by influxdb-srelay user, as this can be a security issue
	chown -Rh root:$INFLUXDB_SRELAY_GROUP /etc/influxdb-srelay/*
	chmod 755 /etc/influxdb-srelay
	find /etc/influxdb-srelay -type f -exec chmod 640 {} ';'
	find /etc/influxdb-srelay -type d -exec chmod 755 {} ';'

  if [ -x /bin/systemctl ] ; then
    echo "### NOT starting on installation, please execute the following statements to configure influxdb-srelay to start automatically using systemd"
    echo " sudo /bin/systemctl daemon-reload"
    echo " sudo /bin/systemctl enable influxdb-srelay.service"
    echo "### You can start influxdb-srelay by executing"
    echo " sudo /bin/systemctl start influxdb-srelay.service"
  elif [ -x /sbin/chkconfig ] ; then
    echo "### NOT starting influxdb-srelay by default on bootup, please execute"
    echo " sudo /sbin/chkconfig --add influxdb-srelay"
    echo "### In order to start influxdb-srelay, execute"
    echo " sudo service influxdb-srelay start"
  fi
elif [ $1 -ge 2 ] ; then
  if [ -x /opt/influxdb-srelay/ ]; then
    echo "### Upgrading Notice ### "
    echo "-- New influxdb-srelay install home is /usr/share/influxdb-srelay"
    #echo "-- Please move sqlite3 database to /var/lib/influxdb-srelay/"
    echo "-- Notice: service name && binary changed to influxdb-srelay"
  fi

  if [ "$RESTART_ON_UPGRADE" == "true" ]; then
    stopInfluxDBSrelay
    startInfluxDBSrelay
  fi
fi
